use_frameworks!
source 'git@192.168.250.71:ios/cocoapods.git'

target 'HookMutableDictionary_Example' do
  pod 'HookMutableDictionary', :path => '../'

  target 'HookMutableDictionary_Tests' do
    inherit! :search_paths

    
  end
end
